[package]
name = "timestamp-example"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
arwa = { workspace = true }
empa = { workspace = true, features = ["arwa", "bytemuck"] }
futures = { workspace = true }
