[workspace]
resolver = "2"
members = [
    "crates/empa",
    "crates/empa_glam",
    "crates/empa_macros",
    "crates/empa_smi",
    "crates/empa_test",
    "examples/risl/native/0_triangle",
    "examples/risl/native/1_animated_triangle",
    "examples/risl/web/0_triangle",
    "examples/risl/web/1_animated_triangle",
    "examples/wgsl/native/0_triangle",
    "examples/wgsl/native/1_animated_triangle",
    "examples/wgsl/native/2_textured_triangle",
    "examples/wgsl/native/3_compute",
    "examples/wgsl/native/4_cube_3d",
    "examples/wgsl/native/5_override_constant",
    "examples/wgsl/web/0_triangle",
    "examples/wgsl/web/1_animated_triangle",
    "examples/wgsl/web/2_textured_triangle",
    "examples/wgsl/web/3_compute",
    "examples/wgsl/web/4_cube_3d",
    "examples/wgsl/web/5_compute_prefix_sum",
    "examples/wgsl/web/6_compute_atomic_array",
    "examples/wgsl/web/7_buffer_projection",
    "examples/wgsl/web/8_persistent_threads",
    "examples/wgsl/web/9_timestamp"
]
default-members = [
    "crates/empa",
    "crates/empa_glam",
    "crates/empa_macros",
    "crates/empa_smi",
    "crates/empa_test",
    "examples/wgsl/native/0_triangle",
    "examples/wgsl/native/1_animated_triangle",
    "examples/wgsl/native/2_textured_triangle",
    "examples/wgsl/native/3_compute",
    "examples/wgsl/native/4_cube_3d",
    "examples/wgsl/native/5_override_constant",
]

[workspace.package]
version = "0.1.1"
edition = "2024"
authors = ["Roland Schermer <roland0507@gmail.com>"]
homepage = "https://github.com/RSSchermer/empa"
repository = "https://github.com/RSSchermer/empa"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
arrayvec = "0.7"
arwa = { path = "../rudo/arwa" }
atomic-counter = "1"
codespan-reporting = "0.13"
compiletest_rs = "0.11"
bytemuck = "1"
empa = { version = "0.1.0", path = "crates/empa" }
empa-glam = { version = "0.1.0", path = "crates/empa_glam" }
empa-macros = { version = "0.1.0", path = "crates/empa_macros" }
empa-smi = { version = "0.1.0", path = "crates/empa_smi" }
flagset = "^0.4"
futures = "0.3"
glam = "^0.30"
hashbrown = "0.16"
include-preprocessor = "0.1"
indexmap = "2"
js-sys = "0.3.82"
lazy_static = "1"
memoffset = "0.9"
naga = "27"
quote = "1"
pin-project = "1"
png = "0.18"
pollster = "0.4"
proc-macro2 = "1.0.69"
raw-window-handle = "0.6"
risl = { version = "0.1.0", path = "../resl2/crates/library/risl" }
risl-request = { version = "0.1.0", path = "../resl2/crates/library/risl_request" }
serde = "1"
syn = "2"
wasm-bindgen = "0.2.105"
wasm-bindgen-futures = "0.4"
web-sys = "0.3.82"
wgc = { package = "wgpu-core", version = "27" }
wgt = { package = "wgpu-types", version = "27" }
winit = "0.30"
