[package]
name = "empa-smi"
description = "Shader Module Interface descriptions based on the WGSL specification."
version = "0.1.2"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[features]
wgsl = ["dep:indexmap", "dep:naga"]
stderr = ["naga?/stderr"]
to-tokenstream = ["dep:proc-macro2", "dep:quote"]

[dependencies]
indexmap = { workspace = true, optional = true }
naga = { workspace = true, optional = true, features = ["wgsl-in"] }
proc-macro2 = { workspace = true, optional = true }
quote = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
