[package]
name = "empa-smi"
description = "Shader Module Interface descriptions based on the WGSL specification."
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[features]
wgsl = ["dep:indexmap", "dep:naga"]
stderr = ["naga?/stderr"]

[dependencies]
indexmap = { workspace = true, optional = true }
naga = { workspace = true, optional = true, features = ["wgsl-in"] }
serde = { workspace = true, features = ["derive"] }
