[package]
name = "empa-smi"
description = "Shader Module Interface descriptions from Empa."
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
serde = { workspace = true, features = ["derive"] }
