[package]
name = "textured-triangle-example-wgsl-native"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
bytemuck = { workspace = true }
empa = { workspace = true, features = ["dx12", "metal"] }
png = { workspace = true }
pollster = { workspace = true }
winit = { workspace = true }
