[package]
name = "empa-macros"
description = "Procedural macros for the empa crate."
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[lib]
proc-macro = true

[features]
risl = ["dep:risl-request"]

[dependencies]
codespan-reporting = { workspace = true }
empa-smi = { workspace = true, features = ["wgsl", "to-tokenstream"] }
include-preprocessor = { workspace = true }
indexmap = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
risl-request = { workspace = true, optional = true }

[dependencies.syn]
workspace = true
features = [
    "full"
]
