[package]
name = "empa-macros"
description = "Procedural macros for the empa crate."
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[lib]
proc-macro = true

[dependencies]
codespan-reporting = { workspace = true }
empa-reflect = { workspace = true }
include-preprocessor = { workspace = true }
naga = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }

[dependencies.syn]
workspace = true
features = [
    "full"
]
