[package]
name = "cube-3d-example-wgsl-native"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
empa = { workspace = true, features = ["dx12", "metal"] }
empa-glam = { workspace = true }
glam = { workspace = true }
pollster = { workspace = true }
winit = { workspace = true }
