[package]
name = "empa-reflect"
description = "Procedural macros for the empa crate."
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
empa-smi = { workspace = true }
indexmap = { workspace = true }
naga = { workspace = true, features = ["wgsl-in"] }
