[package]
name = "empa-glam"
description = "Bridge crate between `empa` and `glam`."
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
empa = { workspace = true }
glam = { workspace = true }
