[package]
name = "compute-example-native"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
empa = { workspace = true, features = ["dx12", "metal"] }
futures = { workspace = true }
pollster = { workspace = true }
